CREATE TABLE IF NOT EXISTS fornecedores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL,
  razao_social TEXT,
  cnpj_cpf TEXT,
  telefone TEXT,
  contato TEXT,
  email TEXT,
  endereco TEXT,
  observacao TEXT,
  user_id UUID NOT NULL,
  responsavel_id UUID REFERENCES app_users(id) ON DELETE SET NULL,
  data_cadastro TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_fornecedores_user_id ON fornecedores(user_id);
CREATE INDEX IF NOT EXISTS idx_fornecedores_responsavel_id ON fornecedores(responsavel_id);
CREATE INDEX IF NOT EXISTS idx_fornecedores_cnpj_cpf ON fornecedores(cnpj_cpf);

ALTER TABLE fornecedores ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Fornecedores SELECT" ON fornecedores;
DROP POLICY IF EXISTS "Fornecedores INSERT" ON fornecedores;
DROP POLICY IF EXISTS "Fornecedores UPDATE" ON fornecedores;
DROP POLICY IF EXISTS "Fornecedores DELETE" ON fornecedores;

CREATE POLICY "Fornecedores SELECT" ON fornecedores
  FOR SELECT
  USING (
    auth.uid() = user_id
    OR auth.uid() = responsavel_id
    OR EXISTS (
      SELECT 1
      FROM app_users
      WHERE app_users.id = auth.uid()
        AND app_users.role IN ('administrador', 'gerente')
        AND app_users.is_active = true
    )
  );

CREATE POLICY "Fornecedores INSERT" ON fornecedores
  FOR INSERT
  WITH CHECK (
    auth.uid() = user_id
    AND (
      responsavel_id IS NULL
      OR EXISTS (
        SELECT 1
        FROM app_users
        WHERE app_users.id = responsavel_id
      )
    )
  );

CREATE POLICY "Fornecedores UPDATE" ON fornecedores
  FOR UPDATE
  USING (
    auth.uid() = user_id
    OR auth.uid() = responsavel_id
    OR EXISTS (
      SELECT 1
      FROM app_users
      WHERE app_users.id = auth.uid()
        AND app_users.role IN ('administrador', 'gerente')
        AND app_users.is_active = true
    )
  )
  WITH CHECK (
    (
      auth.uid() = user_id
      OR auth.uid() = responsavel_id
      OR EXISTS (
        SELECT 1
        FROM app_users
        WHERE app_users.id = auth.uid()
          AND app_users.role IN ('administrador', 'gerente')
          AND app_users.is_active = true
      )
    )
    AND (
      responsavel_id IS NULL
      OR EXISTS (
        SELECT 1
        FROM app_users
        WHERE app_users.id = responsavel_id
      )
    )
  );

CREATE POLICY "Fornecedores DELETE" ON fornecedores
  FOR DELETE
  USING (
    auth.uid() = user_id
    OR EXISTS (
      SELECT 1
      FROM app_users
      WHERE app_users.id = auth.uid()
        AND app_users.role IN ('administrador', 'gerente')
        AND app_users.is_active = true
    )
  );